### ISSUE TITLE
redundant ")"

### ISSUE THREAD

**Issue by Karl-1** [hartenthaler/german-wars-battles-worldwide#1]
Each link in the collection has a superfluous closing bracket at the end. The link then leads to an error. If you remove the bracket then the link is correct.

**Comment by hartenthaler** [comment]
Thanks for your comment! 
This is by design because it uses markdown formatting. A link looks like [text](url). But this only works if you have it enabled for your tree. See Control panel / Manage family trees / Preferences and then scroll down to "Text" and mark the option "markdown". I will update my documentation and will try to modify it in a way that it will even work without markdown enabled, but it will always look better with markdown enabled.

**Comment by Karl-1** [comment]
Thank you very much, it worked immediately! 
I must say that in the two days that I have updated to Webtrees 2, I have received more qualified and rapid help than in any other project before ! I am thrilled! :-)

**Comment by hartenthaler** [comment]
closed

Readme has now a comment about markdown; links are working even if markdown is disabled.
